#spring:
#  application:
#    name:
#piracy:
##Sms配置
##  sms:
##    enable: true
##    regionId: cn-hangzhou
##    accessKey: LTAI4Fz87C9k4dVvigtBWwk5
##    secret: jkEQamTevvkpDwG0VVM9by73DXqTIO
##    phoneNumbers: 19991962259
##    signName: 我只中意你
##    templateCode: SMS_206746676
##钉钉
#  dingding:
#    enable: true
#    msgtype: text
#    phone: 19991962259
#    is-all: true
#    access_token: ac39ef481aff92d19dc21ec6df05e5f2b2a6870e6046f3f95beb5b34110e2a3e
#    secret: SECb202b52aedf7d14fb7f2d40bf76625aef65a64fb1e54d1c82f9aa84cbb6a8077
##钉钉或短信只能配置一个